os: linux
dist: focal
language: c
services: docker
addons:
  hosts:
    - mariadb.example.com

cache:
  apt: true
  ccache: true
  directories:
    - $HOME/docker

before_install:
  - git clone https://github.com/mariadb-corporation/connector-test-machine.git
  # Load cached docker images
  - if [[ -d $HOME/docker ]]; then ls $HOME/docker/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load"; fi

install:
  - |-
    if [ -z "$server_branch" ] ; then
      case $TRAVIS_OS_NAME in
        windows)
          connector-test-machine/launch.bat -t "$srv" -v "$v" -d testc
          ;;
        linux)
          source connector-test-machine/launch.sh -t "$srv" -v "$v" -d testc -l "$local" -n "$native"
          ;;
      esac
    fi


env: local=0

stages:
  - Minimal
  - name: Enterprise
    if: type = push AND fork = false
  - Community

jobs:
  fast_finish: true
  allow_failures:
    - env: srv=maxscale
    - env: srv=skysql
    - env: srv=skysql-ha
    - env: srv=xpand
    - env: srv=mysql v=5.7
    - env: srv=mysql v=8.0
  include:
    - stage: Minimal
      env: srv=mariadb v=10.6 packet=8
      name: "CS 10.6"
    - env: srv=mariadb-es
      name: "ES latest"
      if: type = push AND fork = false
    - env: server_branch=10.11
      name: "10.11 Server unit testing"

    - stage: Enterprise
      env: srv=mariadb-es v=10.4
      dist: bionic
      name: "ES 10.4"
    - env: srv=mariadb-es v=10.5
      dist: bionic
      name: "ES 10.5"
    - env: srv=mariadb-es v=10.6
      name: "ES 10.6"
    - env: srv=mariadb-es-test v=23.08
      name: "ES 23.08"
    - env: srv=maxscale
      name: "Maxscale"
    - env: srv=xpand
      name: "Xpand"

    - stage: Community
      env: srv=mariadb v=10.11
      os: windows
      language: shell
      name: "Windows"
    - env: server_branch=10.6
      name: "10.6 Server unit testing"
    - env: server_branch=11.3 TEST_OPTION=--ps-protocol
      name: "11.3 Server unit testing with ps-protocol"
    - env: srv=mariadb v=10.4 local=1
      dist: bionic
      name: "CS 10.4"
    - env: srv=mariadb v=10.5 local=1
      dist: bionic
      name: "CS 10.5"
    - env: srv=mariadb v=10.9 local=1
      name: "CS 10.9"
    - env: srv=mariadb v=10.10 local=1
      name: "CS 10.10"
    - env: srv=mariadb v=10.11 local=1
      name: "CS 10.11"
    - env: srv=mariadb v=10.11 local=1 TEST_OPTION=--ps-protocol
      name: "CS 10.11 with ps-protocol"
    - env: srv=mariadb v=11.0 local=1
      name: "CS 11.0"
    - env: srv=mariadb v=11.1 local=1
      name: "CS 11.1"
    - env: srv=mysql v=5.7 native=1
      name: "MySQL 5.7"
    - env: srv=mysql v=8.0 native=1
      name: "MySQL 8.0"

script: ./travis.sh
