# coding: utf-8

"""
    WikiDice

    Get a random Wikipedia article under a category

    The version of the OpenAPI document: 1.0.0
    Contact: zelcon@zelcon.net
    Generated by: https://openapi-generator.tech
"""


from fastapi import FastAPI

from openapi_server.apis.default_api import router as DefaultApiRouter

app = FastAPI(
    title="WikiDice",
    description="Get a random Wikipedia article under a category",
    version="1.0.0",
)

app.include_router(DefaultApiRouter)
